# Generated by Django 3.2 on 2021-08-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Toliq Ismingiz')),
                ('tel', models.CharField(max_length=50, verbose_name='Tel')),
                ('message', models.TextField(max_length=500, verbose_name='Xabar')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contactlar',
            },
        ),
        migrations.CreateModel(
            name='Narx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qiymati', models.CharField(max_length=200, verbose_name='Qiymati')),
                ('summasi', models.CharField(max_length=200, verbose_name='Summasi')),
                ('slug', models.SlugField(max_length=1000, unique=True, verbose_name='*')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Xizmat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=1000, unique=True, verbose_name='*')),
                ('img', models.ImageField(upload_to='ixzmat_images/', verbose_name='Image')),
                ('date', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(verbose_name='Text')),
            ],
        ),
    ]
