# Generated by Django 3.2 on 2021-08-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_ru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('tel', models.CharField(max_length=50, verbose_name='Номер')),
                ('message', models.TextField(max_length=500, verbose_name='Сообщения')),
            ],
            options={
                'verbose_name': 'Contact_ru',
                'verbose_name_plural': 'Contactlar_ru',
            },
        ),
        migrations.CreateModel(
            name='Narx_ru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qiymati', models.CharField(max_length=200, verbose_name='обслуживание')),
                ('summasi', models.CharField(max_length=200, verbose_name='Цена')),
                ('slug', models.SlugField(max_length=1000, unique=True, verbose_name='*')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Xizmat_ru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=1000, unique=True, verbose_name='*')),
                ('date', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(verbose_name='Текст')),
            ],
        ),
    ]
